### ISSUE TITLE
State приложения должен находиться в самом приложении

### ISSUE THREAD

**Issue by LehaIvanov** [AkshachRd/words#1]
Сразу обращу внимание, WordsContext будет нужен нам для state-менеджмента приложения, но в этом [коммите](https://github.com/AkshachRd/words/commit/5ba70187ddee27ebb753a42b278b88b0047f36be#diff-eebe6d96a32d0f8cf7fa348ec67e8c42b8ffe92edd994b0579a86744ba59e5cc) он располагается в words-ui, что неправильно. State должен располагаться в words, а в words-ui должны находиться только компоненты, т.е. words-ui служит нам просто как библиотека компонентов, которую чисто теоретически можно будет подключить к любому проекту.

**Comment by AkshachRd** [comment]
Перенёс в words.
