### ISSUE TITLE
В words-ui не должно быть ссылок на words

### ISSUE THREAD

**Issue by LehaIvanov** [AkshachRd/words#4]
https://github.com/AkshachRd/words/blob/dcd03b57e18fb8691a2f70c2ba870ac2307adddf/packages/words-ui/src/components/CardTrainer.tsx#L3

Напомню, что в нашем монорепозитории words-ui - это всего лишь библиотека для построения интерфейса, т.е. она содержит в себе контролы, тему, какие-то утилитный функции, которые в теории могут использоваться в каком-нибудь другом приложении, поэтому бизнес-логики приложения words в words-ui быть не должно.

Необходимо посмотреть по файлам words-ui, чтобы в них не было импорта модулей из words.

Компонента `CardTrainer` должна быть в words, так как она содержит в себе бизнес-логику приложения. Нужно посмотреть, возможно, какие-то ещё компоненты можно перенести в words.

**Comment by AkshachRd** [comment]
Поправил.
