### ISSUE TITLE
Пользуемся автовыводом типов в TS при использовании createUseStyles

### ISSUE THREAD

**Issue by LehaIvanov** [AkshachRd/words#5]
https://github.com/AkshachRd/words/blob/dcd03b57e18fb8691a2f70c2ba870ac2307adddf/packages/words-ui/src/components/Card.tsx#L13

Заметил, что в коде часто встречаются вызовы функции `createUseStyles`  с указанием типов, например:

```
type RuleNames = "card";

type CardProps = {
  children?: ReactNode;
  opacity?: number;
  rotation?: number;
};

const useStyles = createUseStyles<RuleNames, CardProps>({
  card: ({ rotation, opacity }) => ({ ... })
});
```

Можно следующим образом записать, и будет то же самое:

```
type CardProps = {
  children?: ReactNode;
  opacity?: number;
  rotation?: number;
};

const useStyles = createUseStyles({
  card: ({ rotation, opacity }: CardProps) => ({...}),
});
```

Typescript в этом случае сам выведет типы, это позволит нам меньше редактировать кода при внесении изменений.

Необходимо посмотреть по проекту подобные кейсы и исправить их.

**Comment by AkshachRd** [comment]
Разобрался, поправил.
